### ISSUE TITLE
systemd inclusion breaks rpc-statd

### ISSUE THREAD

**Issue by km-bh** [rancher/hyperkube-base#16]
After digging into my issue at https://github.com/rancher/rancher/issues/41601, I found that including systemd in the base image build has unintended consequences for NFS-type volume mounting. Specifically, because the systemctl binary fails to run in a chroot but exits with code 0, it provides a false positive in /usr/sbin/start-statd and thus rpc-statd is never started.

Tests and more details are in the linked issue.

**Comment by superseb** [comment]
I asked the author of the change to check the issue, I will close this.
